# Generated by Django 3.2.9 on 2021-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='club',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
