# Generated by Django 3.2.9 on 2021-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic3', '0002_auto_20211125_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
